version: '3'

services:
  huns-chain-node0:
    image: 'huns-chain:latest'
    container_name: huns-chain-node0
    restart: always
    environment:
      NODE_NAME: node0
      MANAGER_HOST: 10.7.10.151
      NODE_APP_ID: "BLg2VxyZJj2tlfqSadTC1X1R2P31wc750WsWrTBDyuEjH1Tofm/PNruxdLBIG80SJOeUMM3rqRn5IN0g3MwTDYw="
      NODE_PRIVATE_KEY: "mssvlEy8zey1FDnWicIacrZ/gdjGWU/1a5Vd2saKjI4="
    networks:
      bcn:
        ipv4_address: 192.170.0.2
    ports:
      - '38080:38080'
      - '5000:5000'
    volumes:
      - "/tmp/huns-chain-0-logs:/app/logs"

  huns-chain-node1:
    image: 'huns-chain:latest'
    container_name: huns-chain-node1
    restart: always
    environment:
      NODE_NAME: node1
      MANAGER_HOST: 10.7.10.151
      NODE_APP_ID: "BP5AwOvo6PGo3KH/g2pCbjh0xFWrVaDFaRs+gHfPi/Ztd5iRsChjIksdUVYul7Vg9W2j3Hi8DTSNxEygvwztz+M="
      NODE_PRIVATE_KEY: "SZmuOGr1xoj+aX2fZ4CLFCfMOdwN2VvRhZh9SEl7noU="
    networks:
      bcn:
        ipv4_address: 192.170.0.3
    ports:
      - '38081:38080'
      - '5001:5000'
    volumes:
      - "/tmp/huns-chain-1-logs:/app/logs"

  huns-chain-node2:
    image: 'huns-chain:latest'
    container_name: huns-chain-node2
    restart: always
    environment:
      NODE_NAME: node2
      MANAGER_HOST: 10.7.10.151
      NODE_APP_ID: "BPutKJ16zR/ADfc47Zf3WPzK4F+SAdKsKy3sT2DlqP6cA6w1k/gdx97ZJpx3GA1i/0xppB1It9HyThjGqwOHXIw="
      NODE_PRIVATE_KEY: "51d+DbwE1n9ap4z/RI9b2+BKEtCbIK1VtY09VqYtvug="
    networks:
      bcn:
        ipv4_address: 192.170.0.4
    ports:
      - '38082:38080'
      - '5002:5000'
    volumes:
      - "/tmp/huns-chain-2-logs:/app/logs"

  huns-chain-node3:
    image: 'huns-chain:latest'
    container_name: huns-chain-node3
    restart: always
    environment:
      NODE_NAME: node3
      MANAGER_HOST: 10.7.10.151
      NODE_APP_ID: "BMfTIw7JVuNE1gurrCHhcGtliq722wldZxCmI4ic8Lgd/CpdVvNaUpohyD0nhbH/4FBumSPeEoXHf/sSanxWXZw="
      NODE_PRIVATE_KEY: "vLg58fQugEXZl3aoRItR0Llkyf8Egb309TLSRZZUGeU="
    networks:
      bcn:
        ipv4_address: 192.170.0.5
    ports:
      - '38083:38080'
      - '5003:5000'
    volumes:
      - "/tmp/huns-chain-3-logs:/app/logs"

  huns-chain-node4:
    image: 'huns-chain:latest'
    container_name: huns-chain-node4
    restart: always
    environment:
      NODE_NAME: node4
      MANAGER_HOST: 10.7.10.151
      NODE_APP_ID: "BFJTBfOKKHftw7jnU+0c45tDgrCBhCyiFJoi/zv54NSIpoxVxAGaCAaa1wqz9NjIFdYRmnSJen/VYvwr26CyTOY="
      NODE_PRIVATE_KEY: "EJsZq95NXMi8MD5MTkJ3CV0EbCBB/BYih+5YphlAoxs="
    networks:
      bcn:
        ipv4_address: 192.170.0.6
    ports:
      - '38084:38080'
      - '5004:5000'
    volumes:
      - "/tmp/huns-chain-4-logs:/app/logs"

networks:
  bcn:
    ipam:
      config:
        - subnet: 192.170.0.0/16