version: '3'

services:
  manager-mysql:
    image: 'mysql:5.7'
    container_name: manager-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 2858300wc
    volumes:
      - "~/servers/docker/manager-mysql/data/db:/var/lib/mysql"
      - "~/servers/docker/manager-mysql/data/conf:/etc/mysql/conf.d"
    ports:
      - '3306:3306'